### ISSUE TITLE
Log IG publisher QA errors

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#153]
It is not possible to view the errors from the IG publisher when the CI pipeline runs validation. This is because errors end up in `site_root/output/qa.html` which is destroyed along with the rest of the CI environment when the pipeline finishes. 

The publisher seems to output a text version of `qa.html`, `site_root/output/qa.txt`. We should log the content of this file so that the errors are visible in the CI terminal.

**Comment by liberaliscomputing** [comment]
The simplest way of doing this is merely adding `cat site_root/output/qa.txt` to the CI. However, this may not be very informative, given there are usually lots of build errors (called `Broken Links` at the end of log outputs) which don't influence validation. Looking at the [qa.txt](https://github.com/kids-first/kf-model-fhir/files/4702579/qa.txt) file, it is hard to find any flag or indicator that says which is a build error or the other.

**Comment by znatty22** [comment]
First, I think this should be a part of the logs, which means it will have to go in the Python code. Second, I created this issue in the wrong repo :), should be in `ncpi-fhir-utility`.

I think the best way to get the error messages we want and exclude what we don't want would be to extract the lines in `qa.txt` that start with `ERROR` and do not contain `.html`. 

I'm going to move this issue to the correct repo.

**Comment by znatty22** [comment]
Implemented as part of `ncpi-fhir/ncpi-fhir-utility` repo
