### ISSUE TITLE
Design Kids First FHIR Model MVP - v0.1.0

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#23]

**Comment by allisonheath** [comment]
Do we want to close or adjust these issues with the new strategy of starting with the R4 FHIR Resources? Also seems duplicative with #50?

**Comment by znatty22** [comment]
This is an Epic which ties together a bunch of issues, #50, being one of them. I think you have to be signed into Zenhub to see the linked issues

**Comment by znatty22** [comment]
Also per R4 FHIR - we don't know if we can upgrade to this version until we get an answer back on whether there is a Vonk docker image for R4.

**Comment by znatty22** [comment]
Looks like the license file and handling of it by the Vonk server hasn't changed from STU3 to R4. We can just download a new license file from an STU3 simplifier project until this functionality is available on an R4 simplifier project.
