### ISSUE TITLE
Create skeleton FHIR model

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#50]
Empty profiles for the MVP FHIR model:

- Study
- Participant
- Biospecimen
- Phenotype Observation

**Comment by ShahimEssaid** [comment]
Profile validation fails if a "skeletal" profile doesn't actually add any constraints. We'll have to wait on creating these until there is something to actually profile for these resources unless we don't mind the validation errors noise. I'm creating the files anyway so they are at least there to work with.

**Comment by ShahimEssaid** [comment]
Base files created. I added constraints on "identifier" as a temporary constraint to help validate the files. There are a couple of extra resources that are relevant to the above list:

A participant is a FHIR ResearchSubject, and a ResearchSubject refers to a FHIR Patient.
A FHIR ResearchStudy refers to a FHIR Practitioner. I added a file for the practitioner.

**Comment by znatty22** [comment]
Closing since it was decided that Kids First will extend the Phenopackets FHIR model.
