### ISSUE TITLE
Develop & Test Kids First study Resources

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#51]
- [ ] Create StructureDefinition if needed
- [ ] Create any necessary Extensions for added attributes
- [ ] Create SearchParameters for the Extensions from ^
- [ ] Create any necessary CodeSystems or ValueSets

**Comment by liberaliscomputing** [comment]
Dataservice ERD: https://github.com/kids-first/kf-api-dataservice/blob/master/docs/erd.png
