### ISSUE TITLE
Allow both XML and JSON files but prefer one over the other

### ISSUE THREAD

**Issue by ShahimEssaid** [kids-first/kf-model-fhir#54]
Currently the CLI submits both the XML and JSON versions of the same profile, if they both exist. The submission of the second version will fail due to an existing profile with the same ID on the server. The validation errors are distracting from whether or not the first version succeeded. 

It might be useful to keep both XML and JSON versions under version control and only load one of them during validation.

**Comment by allisonheath** [comment]
So I'm going to go out on a limb and say that we should prefer JSON. I think we'll get more buy in if people can work in JSON and it'll make us learn all of the potential gotchas...

**Comment by znatty22** [comment]
So I was thinking about how the CLI should handle the presence of two profiles in different file formats. I think we should keep things very simple: leave it to the user to ensure that they don't have two (or more) of the same profiles being submitted for validation. 

I don't think its worth the effort to add extra logic to the CLI to check for duplicate profiles and only submit JSON versions.

**Comment by ShahimEssaid** [comment]
Sounds good, and I can also use the Forge Windows conversion to try to keep
things in JSON. We don't have any significant content yet to worry about
this too much right now. Maybe later the right choice will become more
obvious.
