### ISSUE TITLE
Decide on model file naming conventions

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#56]
Let's figure out the following: 

```
profiles/Participant.json vs participant.json
profiles/Participant.StructureDefinition.json vs Participant.json
resources/Participant.Resource.json vs Participant.json
profiles/extensions/BiologicalSex.StructureDefinition.json
```

**Comment by ShahimEssaid** [comment]
I think the file names should be as descriptive as possible, and easily relatable to the base FHIR type. Forge suggest the naming I used for the base files. This will be more useful as we start to add other profiling types. But, we might end up with more than one profile per FHIR type so maybe we need to also add some sense of what the profile is about to the file name.

We'll also need a naming convention for the URLs and IDs. Those are more work to change later since other files will refer to these. The file names can be changed later without too much effort.

Another related thought that I had while creating the base files, do we really need profiles at all at this point? The base types are usable as is. They accept any data and any extensions as is. The profiles are only really needed when we want to be more strict. We might be better off creating an ERD based on the base FHIR resources to see how it will look like (there will be more entities involved), and try to populate data. Then we can think about profiles, extensions, terminologies, etc.

**Comment by znatty22** [comment]
> I think the file names should be as descriptive as possible

Agreed. And I'm assuming you mean include things like StructureDefinition in the file name?

> easily relatable to the base FHIR types.

I think I saw you changed the Participant.json profile to Patient.json in your PR. Is this what you mean by easily relatable to the base FHIR types? I'm not so sure about naming profiles according to FHIR base types. If we call it Participant or say, KidsFirstParticipant.StructureDefinition, that tells me a lot more. It says its a profile for a KidsFirst entity called Participant and then  I can look in the file, and see that the profile/constraints are on the FHIR Patient base type.

> We'll also need a naming convention for the URLs and IDs.
Agreed. 

> do we really need profiles at all at this point?

I think we need a little bit. Since we're using this MVP as an exercise to learn FHIR modeling, let's have a few extensions and constraints in our profiles. But I agree, its more important for us to load data in and test out the FHIR API, so let's not get too crazy with our profiles.

**Comment by znatty22** [comment]
> But, we might end up with more than one profile per FHIR type so maybe we need to also add some sense of what the profile is about to the file name.

Remember that we can organize our profiles in different packages/Simplifier projects. And each project will have a base canonical URL (e.g. `http://fhirstu3.kids-first.io/fhir/StructureDefinition/Participant`). So this could be a way we can namespace the profiles too

**Comment by ShahimEssaid** [comment]
> > I think the file names should be as descriptive as possible
> 
> Agreed. And I'm assuming you mean include things like StructureDefinition in the file name?

Yes, the conformance type should be added to the file name but it can be abbreviated to help with readability. Not sure if Forge supports subdirectories. That might be another option.

> I think I saw you changed the Participant.json profile to Patient.json in your PR. Is this what you mean by easily relatable to the base FHIR types? I'm not so sure about naming profiles according to FHIR base types. If we call it Participant or say, KidsFirstParticipant.StructureDefinition, that tells me a lot more. It says its a profile for a KidsFirst entity called Participant and then I can look in the file, and see that the profile/constraints are on the FHIR Patient base type.

Sure, I only changed it to match what I did with the other files. Also, participant is vague in FHIR. There is Patient and Practicioner. These are two different entities and there is no sense for "Person" regardless of their role. Also, a Patient is not directly referenced in a ResearchStudy. Instead, ResearchParticipant is the link, and it then references Patient. I think I got the FHIR names correct here but you get the idea. 

> > do we really need profiles at all at this point?
> 
> I think we need a little bit. Since we're using this MVP as an exercise to learn FHIR modeling, let's have a few extensions and constraints in our profiles. But I agree, its more important for us to load data in and test out the FHIR API, so let's not get too crazy with our profiles.

Right, but we can capture what is needed in the profiles in a simpler format, and Excel sheet for example, to list the missing properties, any possible constraints on existing fields, etc, assign them names, text descriptions, URIs, etc. (all the stuff that will be needed for a real profile) and then use this to create the profiles when we really need them. I'm not saying that we shouldn't use this as an exercise to learn FHIR but we don't really need them to take the next steps for standing up a server, adjusting code to populate it, etc.

**Comment by ShahimEssaid** [comment]
> 
> 
> > But, we might end up with more than one profile per FHIR type so maybe we need to also add some sense of what the profile is about to the file name.
> 
> Remember that we can organize our profiles in different packages/Simplifier projects. And each project will have a base canonical URL (e.g. `http://fhirstu3.kids-first.io/fhir/StructureDefinition/Participant`). So this could be a way we can namespace the profiles too

We might be thinking about different things when we say "profile". I use it to refer to each conformance resource file, not to the overall KF FHIR profile. Is that what you mean too? My earlier comment meant that we might have more than one StructureDefinition per same base FHIR type and having both the base type and the "sense" of our KF profile over it in the file name might be helpful.

However, we probably should follow some best practices with all this. I'm not sure if the spec gives some guidance, or if the community has adopted some patterns.

**Comment by ShahimEssaid** [comment]
An Excel sheet will also be a simple way to start documenting mappings fro the current ERD to the base FHIR model and any KF profiling items. Is there a better way to start capturing a summary/high-level view of this knowledge in addition to our GitHub threads?

**Comment by allisonheath** [comment]
Google sheets perhaps - as a place to start/collaborate until we get to a more nailed down version we want to use?

**Comment by znatty22** [comment]
After trying to work with the US Core R4 model: https://simplifier.net/specialtyfhir4, I'm realizing it it might be useful to follow a naming convention like this:

Examples:
`kids_first.r4.patient.structure_definition.json`
`kids_first.r4.proband_status.structure_definition.extension.json`
`kids_first.r4.patient.json`

1. Consistent casing
2. Provides Context:
- Project name (e.g. kids first)
- FHIR version (e.g. 4.0.0) or name (e.g. r4)
- Resource type (e.g. patient, specimen, structure definition, search parameter, etc)

We could look in the file to get all of that ^ info, but its not very convenient for quick browsing, searching, and sorting.

The US Core R4 model looks like this (shortened for brevity): 
```
├── Patient-example.json
├── USCoreEthnicityExtension.json
├── USCorePatientProfile.json
├── USCoreRaceExtension.json
├── us-core-ethnicity.json
├── us-core-patient-birthdate.json
├── us-core-patient-family.json
├── us-core-patient-gender.json
├── us-core-patient-given.json
├── us-core-patient-id.json
├── us-core-patient-identifier.json
├── us-core-patient-name.json
```

As you can see it's tough to tell that `us-core-ethnicity.json` is a search parameter vs an extension, and that it's a FHIR R4 resource.

**Comment by ShahimEssaid** [comment]
I just want to add that the IG Publisher also has some expectations about the file naming, mostly it's a combination of the resource type and the resource id. I can't say more right now because I still haven't figured out the details yet.

**Comment by ShahimEssaid** [comment]
I changed the name of the StructureDefinition-Participant.json and this is what the publisher says because it couldn't find it after the name change:

```
Unable to find the source file for StructureDefinition/Participant: not specified, so tried 
StructureDefinition-Participant.xml, 
Participant.StructureDefinition.xml, 
StructureDefinition-Participant.json, 
StructureDefinition/Participant.xml, 
StructureDefinition/Participant.json, 
Participant.xml, and 
Participant.json 
(and lowercase resource name variants) 
in dirs [/data/source/resources/implementationguide, /data/source/resources, /data/source/examples]
```

The above shows the default search based on giving the Type/id values in ig.json:

```
"resources": {
    "StructureDefinition/Participant": {
      "base": "StructureDefinition-Participant.html",
      "defns": "StructureDefinition-Participant-definitions.html"
  }
```

But if a "source" is given as in:

"resources": {
    "StructureDefinition/Participant": {
      "source": "StructureDefinition-Particip.json",
      "base": "StructureDefinition-Participant.html",
      "defns": "StructureDefinition-Participant-definitions.html"
  }
```
then that file will be used for the StructureDefinition. The generated files will follow the Type/id pattern and a file named StructureDefinition-Participant.json (xml, ttl) will be generated. So, given the generated file name we should probably follow the same pattern to make it easier to related source file names to generated file names (i.e. the same names) but we can follow any naming patterns we like for source files as long as we specify a "source".

**Comment by ShahimEssaid** [comment]
For the example file, the source file name should be "Patient-participant-example.json" to avoid needing a "source" in ig.json.
