### ISSUE TITLE
Should we fail validation on non-existent referenced resources? 

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#58]
Let's take the following example. I'm using the base FHIR [Specimen profile](http://hl7.org/fhir/STU3/specimen.html) which requires that a Specimen resource has a reference to a Patient resource. 

The FHIR server only validates the presence of the reference attribute but not the value of it - or essentially, whether the resource being referenced in the value actually exists on the server. For example, here is a Specimen resource that passes validation:
```
{
    "resourceType":"Specimen",
    "meta": {
        "profile": "http://fhirstu3.kids-first.io/fhir/StructureDefinition/Specimen"
    },
    "subject": {
        "reference": "ResearchSubject/test_study-p001"
    },
    "identifier": {
        "value": "bs001"
    }
}
```
This ResearchSubject `ResearchSubject/test_study-p001` doesn't actually exist on the server. 
Should we add validation logic in the CLI to check for this or leave it alone?

**Comment by fiendish** [comment]
>  I'm using the base FHIR Specimen profile

That's the 3.0 profile. The 4.0 profile has no such restriction https://www.hl7.org/fhir/specimen.html

**Comment by allisonheath** [comment]
Yea, we should follow R4 if we can (I realize most things are still STU3), but in this case yep let's leave it alone. Is it possible to warn versus fail?

**Comment by fiendish** [comment]
FHIR as a spec intentionally leaves business requirements logic in our hands, so we can do whatever we want either on the client side or via intermediate validation passthrough service. I vote to leave reference existence unrestricted for now, and we can change our behavior if we see that it causes more problems than it solves.

**Comment by znatty22** [comment]
> Is it possible to warn versus fail?

Its definitely possible. It requires the same effort/code to as it would if we were going to fail validation. We would have to write some logic that searches resource JSON payloads for "reference" keys and then tries to search the server for them. 

I vote we leave reference existence unrestricted for now too

**Comment by znatty22** [comment]
Consensus seems to be leave the reference existence unvalidated for now. Closing this out

**Comment by fiendish** [comment]
Reopening this. When you say "The FHIR server", which fire server do you mean? The SMART on FHIR public sandbox at https://r4.smarthealthit.org/ for instance does validate references.

**Comment by znatty22** [comment]
Interesting, then that means the SMART FHIR server implementation chose to validate references..and as of now the Firely FHIR server (or Vonk) does not. I wonder if there is a setting or something to change that 🤔
