### ISSUE TITLE
Upgrade to FHIR R4

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-model-fhir#59]
I'm starting a new issue for this just so we can keep track of the rational for our decision. 

When I first started looking into FHIR there were a couple reasons I opted to start with STU3 rather than R4:

1. Forge R4 was not able to connect to simplifier and load profiles (e.g. US Core, Simplifier Core, etc). It looks like they just released (yesterday!) a version of Forge that is able to do this: https://simplifier.net/organization/firely/news/76

2. Vonk R4 - I didn't see a way to access an R4 docker image license for Vonk. Currently, on my STU3 Simplifier project I can go to my project home page > Download > NatashaSTU3Workspace FHIR Server and download the zip file containing the Vonk docker compose file and license for FHIR STU3. This is not available for a R4 Simplifier project (I don't seem to have that same button on my R4 project page). 

I also tried to go to the simplifier Docker Hub page to look for R4 images, but there isn't a clear way to tell whether the image tags correspond to FHIR version numbers.

There is some talk of Vonk R4 on Zulip fhir chat, so it might exist. I'm going to post a question to see if a Vonk R4 docker image exists.

**Comment by znatty22** [comment]
Looks like Vonk [Release 3.0.0-beta2](http://docs.simplifier.net/vonk/releasenotes/releasenotes.html#release-3-0-0-beta2) is the latest one that supports FHIR R4. It actually supports multiple FHIR versions including STU3. Its default mode is STU3 so extra steps need to be taken to instruct the server on R4 operation.

Upgrading to Vonk R4 requires: 
- [ ] Update docker-compose file to point to `simplifier/vonk:3.0.0-beta2` or `simplifier/vonk:stable` if this is a stable version that supports R4.
- [ ] Update appsettings.json with `Vonk.Fhir.R4`
- [ ] Update appsettings.json with mongo db name =`vonkdata`
- [ ] Set header fhirVersion=4.0 in POST/PUT requests. See details [here](http://docs.simplifier.net/vonk/features/multiversion.html#feature-multiversion)

**Important Note** 
Terminology operations not supported in R4. See details [here](http://docs.simplifier.net/vonk/features/terminology.html#feature-terminology)

**Comment by allisonheath** [comment]
I would also be curious about the Aidbox and HAPI R4 status as well?

**Comment by znatty22** [comment]
It doesn't seem like Aidbox supports R4 yet - See https://docs.aidbox.app/installation/setup-aidbox.dev. They recommend setting the FHIR VERSION env var to 3.0.1 in the docker-compose file and the other version numbers don't go above 3.3.0.
