### ISSUE TITLE
Create mappings between Kids First and FHIR Phenopackets

### ISSUE THREAD

**Issue by liberaliscomputing** [kids-first/kf-model-fhir#74]
Create mappings between KF and FHIR Phenopackets models, using [this spreadsheet](https://docs.google.com/spreadsheets/d/19tQnE75UzvP_k29D-QprbsJ-6ZO2PdUmKPiWHKkcTEg/edit?usp=sharing). This is part of https://github.com/d3b-center/clinical-data-flow/issues/15. The followings are an order of actions:

- [x] @liberaliscomputing will populate Column A (KF Concept Attribute) against the intermediate PCGC data persisted in [the KF Warehouse DB](http://10.10.1.191:5431). The KF data service REST documentation is also available [here](https://kf-api-dataservice.kidsfirstdrc.org/);
- [x] @liberaliscomputing and @ShahimEssaid will 1) split Participant, Observation, and Specimen resources and 2) map  KF concept attributes and FHIR model attributes, using Phenopackets; and

**Comment by znatty22** [comment]
Closing this since its complete and we are moving on to developing a Kids First FHIR model from scratch.
